### PR TITLE
To align with coding style and formatting within laravel's config/*.php ...

### PR DESCRIPTION
**Pull request by piengeng**
...or vendor/laravel/**/*.php

 - minor none DocBlock space deletion.
 - align = and => symbol, considered 2nd highest position to align with, using ratio of 1.5, only top 5 or lower

Did not upload my own testing files. Anyhow, it's still experimental.

### CODE REVIEW

**Comment by dericofilho** [comment]
Hi! Before I accept this PR I need to know if you are willing to become the maintainer of LaravelStyle Additional pass. If so, I will accept without tests.

Otherwise, I will need you to provide with tests in order to accept this PR.

**Comment by piengeng** [comment]
erm, i'll need to study how to include tests for my codes... is it difficult? I'll become maintainer on my codes. no problem.

**Comment by dericofilho** [comment]
@piengeng All you need to do is add test files in src/tests/
Copy these two files renaming them, and increasing the counter before the name.
https://github.com/dericofilho/php.tools/blob/master/src/tests/189-laravel-style.in
https://github.com/dericofilho/php.tools/blob/master/src/tests/189-laravel-style.out

After you have added the files, run:
```
cd src;
php test.php -v
```

This should do for start - I am ready to support you in anything you need.

**Comment by piengeng** [comment]
i'll try and add into the test folder

**Comment by dericofilho** [comment]
@piengeng OK! Any support needed, just let me know.

**Comment by piengeng** [comment]
No more update from my side.

**Comment by piengeng** [comment]
quite new to github, not sure what to press. haha.

**Comment by dericofilho** [comment]
OK! Now it is my part... I will merge this into master through a branch. All you need to do now is wait until I finish. I will post here the commit of merge as soon as I do it.

**Comment by piengeng** [comment]
Cool, anyway, thanks for this great tool, it helps a lot!

**Comment by dericofilho** [comment]
@piengeng thank you!

Merged by https://github.com/dericofilho/php.tools/commit/a492012e23f20ef792c7ec8635fd2dd7ac7c189d

**Comment by piengeng** [comment]
You're welcomed :) My alignment functions actually produce:- (my actual test/265.xxxx.out)
```
function test()
{
	$one    = 1;
	$twelve = 100;
	$moneyisevil = 'text';

	$moneyisnotevil = 'text';

	$one    = 1;
	$twelve = 100;
	$moneyisevil = 99999999999;
	$moneyisnotevil = 4;

	return array(

		'debug2' => true,

		/*
		|--------------------------------------------------------------------------
		| Application URL as per laravel's app/config/app.php
		|--------------------------------------------------------------------------
		| left bottom corner, that little space that should be removed
		*/
		'aliases' => array(
			'App'     => 'Illuminate\Support\Facades\App',
			'Artisan' => 'Illuminate\Support\Facades\Artisan',
			'Auth'    => 'Illuminate\Support\Facades\Auth',
			'Blade'   => 'Illuminate\Support\Facades\Blade',

			'Cache'             => 'Illuminate\Support\Facades\Cache',
			'ClassLoader'       => 'Illuminate\Support\ClassLoader',
			'Config'            => 'Illuminate\Support\Facades\Config',
			'Controller'        => 'Illuminate\Routing\Controller',
			'Lang'              => 'Illuminate\Support\Facades\Lang',
			'Route'             => 'Illuminate\Support\Facades\Route',
			'Schema'            => 'Illuminate\Support\Facades\Schema',
			'Seeder'            => 'Illuminate\Database\Seeder',
			'Session'           => 'Illuminate\Support\Facades\Session',
			'SoftDeletingTrait' => 'Illuminate\Database\Eloquent\SoftDeletingTrait',
			'SSH'               => 'Illuminate\Support\Facades\SSH',
			'Str'               => 'Illuminate\Support\Str',
			'URL'               => 'Illuminate\Support\Facades\URL',
			'Validator'         => 'Illuminate\Support\Facades\Validator',
			'View'              => 'Illuminate\Support\Facades\View',

			// manual for external libraries
			'Carbon' => 'Carbon\Carbon',
		),

		$aliases = array(
			'app'            => 'Illuminate\Foundation\Application',
			'artisan'        => 'Illuminate\Console\Application',
			'auth'           => 'Illuminate\Auth\AuthManager',
			'auth.reminder.repository' => 'Illuminate\Auth\Reminders\ReminderRepositoryInterface',
			'blade.compiler' => 'Illuminate\View\Compilers\BladeCompiler',
			'cache'          => 'Illuminate\Cache\CacheManager',
			'cache.store'    => 'Illuminate\Cache\Repository',
			'config'         => 'Illuminate\Config\Repository',
			'cookie'         => 'Illuminate\Cookie\CookieJar',
			'encrypter'      => 'Illuminate\Encryption\Encrypter',
			'db'             => 'Illuminate\Database\DatabaseManager',

		),
	);
}
```
The reason behind is because I'm using phpfmt to auto format every time i save a php file. And the annoying thing about phpfmt is, that it's modifying original lines more than it should. Thus, the alignment functions is very different with AlignEquals class. I needed the alignment to be flexible,so i'm using 
https://github.com/laravel/laravel/blob/master/app/config/app.php and https://github.com/laravel/framework/blob/4.2/src/Illuminate/Foundation/Application.php to get back the equals alignment. I'd like to think my version is cleaner. 'auth.reminder.repository' => ..." line is escaped, consecutive '=' is linked together. When saving any laravel related files it doesn't overwrite it with phpfmt's formatting. 

Readability and diff purpose (less 'diff' is more) is the primary reason why I'd like to contribute on this tool. That's all I'd like to say. 

Cheers :)

**Comment by dericofilho** [comment]
@piengeng I see your point. It makes sense - I have not released a new version since merge, I will, ASAP, revert this particular change and release it. Thanks for pointing the difference.

**Comment by piengeng** [comment]
@dericofilho Thanks for your understanding and not rejecting it totally, appreciate it, a lot :), Worst case, I can still build the sublime-phpfmt myself right?!

**Comment by dericofilho** [comment]
@piengeng Sure! I understand your point. Go ahead and fork - I want see diversity in PHP ecosystem, for me the more people innovating and extending, the better.

**Comment by dericofilho** [comment]
@piengeng please, take a look at https://github.com/dericofilho/php.tools/commit/ab6169f5a6047636b44a490ef33943095cfe03fd and see if it is better now.

**Pull request closed without merging**
