### PR TITLE
clean up and re-factor my edits,

### PR DESCRIPTION
**Pull request by piengeng**
new classes in src/Laravel/ and tests in src/tests-laravel/

src/laratests.php and src/laratests/
for :- check laravel existing coding style and base for references, strictly testing.
!for :- merging to parent

@dericofilho please consider this PR, please ignore the laratests*.file/folder
only these
>>src/fmt.src.php 
>>src/Laravel/* ignore LaravelStyleNew.php (my testing)
>>src/tests-laravel/*

Some older laravel test will fail, I did not modify on that, hoping you could edit it. My added tests are passing.

### CODE REVIEW

**Comment by dericofilho** [comment]
@piengeng OK! I will merge this into a branch before taking it into master. I shall address it along the day.

**Comment by dericofilho** [comment]
@piengeng vetoes lifted on 76aefd045ab888aecc105b9d7f2decfd805f716b

However this code is still subject to review because it still use regex.

**Comment by piengeng** [comment]
np, however, the regex is on token, not raw text, so html inline issue might not creep up so soon, i think. Regex is more natural to me compared to studying FormatterPass :)

**Comment by dericofilho** [comment]
@piengeng I think that your contribution is good. I just tried to break it in few ways and it hold itself fine - except for handling futile tokens, like T_COMMENT between the variable and the `=`. But this is an initial implementation, in proper time we shall have it good. Thanks @piengeng for the contribution.

**Comment by piengeng** [comment]
@dericofilho Thanks for adding me as contributor. Anyway, your codes are a hell lot structured!

Could you update a line to master? it's missing the T_DOUBLE_ARROW, as the class AlignEqualsByConsecutiveBlocks treats = and => alike, i assume that should work.. not yet tested myself. 
```php
class AlignEqualsByConsecutiveBlocks extends FormatterPass {
	public function candidate($source, $foundTokens) {
		if (isset($foundTokens[ST_EQUAL]) || isset($foundTokens[T_DOUBLE_ARROW])) {
```
anyhow, I'll work on the laravel/framework styles, since i'd only touched the laravel/laravel.

**Comment by dericofilho** [comment]
@piengeng please, open a PR with this change and I will merge it.

**Pull request closed without merging**
